### ISSUE TITLE
Another Wi-Fi module

### ISSUE THREAD

**Issue by Nuqvxz** [morgendagen/riden-dongle#44]
This firmware is made for the "old" Wi-Fi module W01 (assembled on ESP8266).
New Wi-Fi modules W02 are made on ESP8684:
https://ae01.alicdn.com/kf/Ae1ca4d7031594258bdfa43b41e3bf894U.jpg_800x800.jpeg_.webp
Is it possible to write firmware for this module?

**Comment by morgendagen** [comment]
I am afraid that will not be an easy fix since the ESP8684/ESP32-C2 is not very well supported by Arduino and PlatformIO.

I have no way of testing a firmware myself so I will not undertake this task. But I will happily merge a pull request.

**Comment by Nuqvxz** [comment]
Will unsolder ESP8684 and solder ESP-12F.
