### ISSUE TITLE
Power output value is truncated

### ISSUE THREAD

**Issue by hrandib** [morgendagen/riden-dongle#47]
Power output value uses 2 holding registers, all the models that can yield more than 655W are affected.
See https://github.com/morgendagen/riden-dongle/issues/43

**Comment by morgendagen** [comment]
Hi @hrandib,

Thank you for looking in to this. Are you able to provide a pull request? I'd be happy to merge it :)

**Comment by hrandib** [comment]
It'll take some time

**Comment by hrandib** [comment]
Didn't manage to compile the project out of the box. ESP libraries in PIO have been updated:
-    WiFiClient newClient = tcpServer.accept();
+    WiFiClient newClient = tcpServer.available();

-    uint32_t uart_baudrate = std::strtoull(uart_baudrate_string.c_str(), nullptr, 10);
+    uint32_t uart_baudrate = strtoull(uart_baudrate_string.c_str(), nullptr, 10);
